;------------------------------------------------------------------------------
;
; Auto correct for Windows
;
; Still a WIP
;
;------------------------------------------------------------------------------

#NoEnv

;not in a specific order

:*:acomodate::accommodate
:*:accomodate::accommodate
:*:acommodate::accommodate
:*:acnowlege::acknowledge
:*:acnowledge::acknowledge
:*:acknowlege::acknowledge
:*:aknowlege::acknowledge
:*:acheve::achieve
:*:acheive::achieve
:*:aquit::acquit
:*:adress::address
:*:atlete::athlete
:*:aparent::apparent
:*:aint::ain't
:*:alot::a lot
:*:arent::aren't
:*:arne't::aren't
; I always get assassin wrong :D
:*:asasin::assassin
:*:assasin::assassin
:*:asassin::assassin
:*:assassins::assassin's
:*:cant'::can't
:*:cant::can't
:*:catgory::category
:*:cleint::client
:*:changable::changeable
:*:collegue::colleague
:*:cemetary::cemetery
:*:comitment::commitment
:*:concious::conscious
:*:criticise::criticize
:*:cmon::c'mon
:*:couldnt::couldn't
:*:definitly::definitely
:*:disapear::disappear
:*:decieve::deceive
:*:dumbell::dumbbell
:*:embaras::embarrass
::embarras::embarrass
:*:embarass::embarrass
:*:existance::existence
:*:existanse::existence
:*:existense::existence
:*:equiptment::equipment
:*:familar::familiar
:*:facinating::fascinating
:*:foreward::foreword
:*:forword::forward
:*:greatful::grateful
:*:hipocrite::hypocrite
:*:manuever::maneuver
:*:maintanance::maintenance
:*:maintenanse::maintenance
:*:mispell::misspell
::mispel::misspell
:*:misterious::mysterious
:*:miniscule::minuscule
:*:milenials::millennials
:*:millenials::millennials
:*:milennials::millennials
:*:millenium::millennium
:*:milennium::millennium
:*:milenium::millennium
:*:necesary::necessary
:*:neccesary::necessary
:*:neccessary::necessary
:*:ocasion::occasion
:*:occassion::occasion
:*:ocurred::occurred
:*:occured::occurred
:*:ocured::occurred
:*:oddyssey::odyssey
:*:personel::personnel
:*:proced::proceed
:*:preceed::precede
:*:persevarance::perseverance
:*:peice::piece
:*:possesion::possession
:*:pronounciation::pronunciation
:*:recive::receive
:*:recieve::receive
:*:reconize::recognize
:*:rasberry::raspberry
:*:rhime::rhyme
:*:rhytm::rhythm
:*:sissors::scissors
:*:scisors::scissors
:*:sinserely::sincerely
:*:scedule::schedule
:*:suprise::surprise
:*:shouldnt::shouldn't
:*:treshold::threshold
::teh::the
:*:truely::truly
:*:jealus::jealous
:*:jewelry::jewelry
:*:knowlege::knowledge
:*:vilage::village
:*:wich::which
:*:wierd::weird
:*:wether::whether
:*:wensday::wednesday
:*:liek::like
:*:libary::library
:*:paralel::parallel
:*:intepreter::interpreter
:*:interpeter::interpreter
:*:interpetation::interpretation
:*:intepretation::interpretation
:*:yuotube::youtube
